services:
  mongodb:
    container_name: wow-prog-db
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    container_name: wow-prog-backend
    build: ./backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/wow_guild_tracker
      - NODE_ENV=development
    depends_on:
      - mongodb
    volumes:
      - ./backend/public/icons:/app/public/icons
      - ./backend/logs:/app/logs

  frontend:
    build: ./frontend
    container_name: wow-prog-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - API_URL=http://backend:3001
      - NODE_ENV=development
    depends_on:
      - backend

volumes:
  mongodb_data:
